#!/bin/sh
# Script to tidy exim databases.
#
# Copyright (c) 2009 MailHub4U.com, LLC
#
/usr/sbin/exim_tidydb -t 7d /var/spool/exim callout;
/usr/sbin/exim_tidydb -t 10d /var/spool/exim ratelimit;
/usr/sbin/exim_tidydb -t 30d /var/spool/exim retry;
/usr/sbin/exim_tidydb -t 30d /var/spool/exim wait-remote_smtp;
