#!/bin/sh
# Script to tidy exim databases.
#
# Copyright, 2009, by Gordon Dickens and MailHub4u.com, LLC.
#
/usr/sbin/exim_tidydb -t 7d /var/spool/exim callout;
/usr/sbin/exim_tidydb -t 10d /var/spool/exim ratelimit;
/usr/sbin/exim_tidydb -t 30d /var/spool/exim retry;
/usr/sbin/exim_tidydb -t 30d /var/spool/exim wait-remote_smtp;
