#!/bin/sh
# Copyright (c) 2011 MailHub4U.com, LLC
#
# Install exim4u preferences in webmail
#
echo;echo "This script installs exim4u's custom preferences into Horde webmail's configuation files.";echo
# Get data from terminal.
echo -n "Enter webmail home directory: (example: /home/exim4u/public_html/webmail): ";read webmail_dir;
#
cp ./config/* $webmail_dir/config
cp ./imp/config/* $webmail_dir/imp/config
